import React from "react";
import Link from "next/link";
import Step from "@/page/Step";
import Signup from "@/pages/Signup";
import Head from 'next/head';
function loan1() {
  const [modalShow, setModalShow] = React.useState(false);

  return (
    <>
   <Head>
  <title>Terms of Use </title>
  <meta name="description" content="Review our Terms of Use to understand the guidelines and policies governing your use of our services. Learn about your responsibilities, limitations, and how we protect your rights while using our platform." />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</Head>


  <div className='container-fluid privacy'> 
    <div className="row">
    <div className="col-sm-12 col-md-12 mx-5 mt-3">
                <Link href="/" style={{textDecorationLine:"none"}}><span className="home">Home<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-chevron-right" viewBox="0 0 16 16">
          <path fillRule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"/>
        </svg></span></Link>
                {/* <span className="home">Footer <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-chevron-right" viewBox="0 0 16 16">
          <path fillRule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"/>
        </svg></span> */}
       <span className="home text-danger">Terms of use </span>
       </div>
<div className='conventional-loans' >
            <img src="./assets/images/home-page/Terms.jpg" alt=""  className="img-fluid w-100"/>
       </div>

    <div className="col-sm-12 col-md-12">    
   <div className="term-paddingleft">
    <p className='loan1'>Binding Effect</p>
    <p > This is a binding agreement. By using this Internet site (the “Website” or “Site”) or any services provided in connection with the Site (the “Service”),
       you agree to abide by these loan1 of Use, as they may be amended by HomeRatesYard (“Company”) from time to time in its sole discretion. 
       Company will post a notice on the Site any time these loan1 of Use have been changed or otherwise updated. It is your responsibility to 
       review these loan1 of Use periodically, and if at any time you find these loan1 of Use unacceptable, you must immediately leave the Site and 
       cease all use of the Service and the Site. <br/>
       YOU AGREE THAT BY USING THE SERVICE YOU REPRESENT THAT YOU ARE AT LEAST 18 YEARS OLD AND THAT YOU ARE LEGALLY ABLE TO ENTER INTO THIS AGREEMENT.
    </p>

    <p className='loan1'>Privacy Policy</p>
    <p >Company respects your privacy and permits you to control the treatment of your personal information. A complete statement of HomeRatesYard, 
    Inc’s current privacy policy can be found by clicking here. HomeRatesYard’s privacy policy is expressly incorporated into this Agreement by this
    reference. When you are required to open an account to use or access the Site or Service, you must complete the registration process by providing 
    the complete and accurate information requested on the registration form. You will also be asked to provide a username and password. You are 
    entirely responsible for maintaining the confidentiality of your password. You may not use the account, username, or password of someone else at any time. 
    You agree to notify Company immediately of any unauthorized use of your account, username, or password. Company shall not be liable for any loss that you
    incur as a result of someone else using your password, either with or without your knowledge. You may be held liable for any losses incurred by Company, 
    its affiliates, officers, directors, employees, consultants, agents, and representatives due to someone else’s use of your account or password.</p>

    <p className='loan1'>Use of Software</p>
    <p >Company may make certain software available to you from the Site. If you download software from the Site, the software, including all 
    files and images contained in or generated by the software, and accompanying data (collectively, “Software”) are deemed to be licensed to you by Company, 
    for your personal, noncommercial, home use only. Company does not transfer either the title or the intellectual property rights to the Software, and Company 
    retains full and complete title to the Software as well as all intellectual property rights therein. You may not sell, redistribute, or reproduce the Software, 
    nor may you decompile, reverse-engineer, disassemble, or otherwise convert the Software to a human-perceivable form. All trademarks and logos are owned by Company, 
    or its licensors/business partners and you may not copy or use them in any manner.</p>

    <p className='loan1'>User Content</p>
    <p >You grant Company a license to use the materials you post to the Site or Service. By posting, downloading, displaying, performing, transmitting, or otherwise
    distributing information or other content (“User Content”) to the Site or Service, you are granting Company, its affiliates, officers, directors, employees, 
    consultants, agents, and representatives a license to use User Content in connection with the operation of the business of Company, its affiliates, officers, 
    directors, employees, consultants, agents, and representatives, including without limitation, a right to copy, distribute, transmit, publicly display, publicly perform, 
    reproduce, edit, translate, and reformat User Content. You will not be compensated for any User Content. By posting User Content on the Site or Service, you warrant and 
    represent that you own the rights to the User Content or are otherwise authorized to post, distribute, display, perform, transmit, or otherwise distribute User Content. </p>
     
    <p className='loan1'>Website Content</p>
    <p >This website may provide general information about our products and services. Your eligibility for particular products and services is subject to our final determination, 
    restrictions, and acceptance. You agree to accept our final determination and conditions. We may discontinue or make changes to the information, products, licenses, 
    or services described on this website at any time. Any dated information is published as of its publication date only. We do not undertake any obligation or responsibility 
    to update or amend any such information. We reserve the right to terminate any or all offerings without prior notice. Furthermore, by offering information, products, 
    or services via this website, no solicitation is made by us to any person to use such information, products, or services in jurisdictions where the provision of information, 
    products, or services is prohibited by law. </p>
    
    <p >This website may contain links to third-party websites, such as social media websites, which we do not own or control, but which are provided for your convenience. 
    If you visit a link to another website, you do so at your own risk subject to the loan1 and conditions established by the operator of that website. The fact that we 
    provide a link to a website does not mean we endorse, authorize, or sponsor that third-party website, or that we are affiliated with the third-party website’s owners 
    or sponsors. We reserve the right to terminate a link to a third-party website at any time.</p>

    <p>Although we try to provide accurate and timely information on this website, there may be inadvertent, technical, or factual inaccuracies and typographical errors. 
    For these reasons we cannot warrant the accuracy, completeness, or timeliness of the information, text, graphics, links, or other items on this website.</p>

    <p className='loan1'>Compliance with Intellectual Property Laws</p>
    <p> When accessing the Site or using the Service, you agree to obey the law and to respect the intellectual property rights of others. Your use of the Service and 
    the Site is at all times governed by and subject to laws regarding copyright ownership and use of intellectual property. You agree not to upload, download, display, 
    perform, transmit, or otherwise distribute any information or content (collectively, “Content”) in violation of any third party’s copyrights, trademarks, or other 
    intellectual property or proprietary rights. You agree to abide by laws regarding copyright ownership and use of intellectual property, and you shall be solely 
    responsible for any violations of any relevant laws and for any infringements of third-party rights caused by any Content you provide or transmit, or that is 
    provided or transmitted using your user identifying information. The burden of proving that any Content you provide or transmit does not violate any laws or 
    third-party rights rests solely with you.</p>

    <p >This website’s content, including but not limited to all sounds, images, icons, text, software, logos, expressions, and ideas, is copyrighted, and protected by U.S. 
    and worldwide copyright laws and treaty provisions. In addition, this website’s content is protected by patent and trademark laws, the laws of privacy and publicity, 
    and the various communication regulations and statutes. You are not authorized to post on or transmit to or from this website any unlawful, threatening, libelous, defamatory, 
    obscene, scandalous, inflammatory, pornographic, immoral, or profane material, or any other content that could give rise to any civil or criminal liability under the law</p>

    <p >Any commercial use of this website or its content is prohibited. You may print a copy of the information contained on this website only for your personal use. 
    This right may be revoked at any time.</p>

    <p className='loan1'>Inappropriate Content</p>
    <p >You shall not make the following types of Content available. You agree not to upload, download, display, perform, transmit, or otherwise distribute any Content that <br/>
    (a) is libelous, defamatory, obscene, pornographic, abusive, or threatening;<br/>
    (b) advocates or encourages conduct that could constitute a criminal offense, give rise to civil liability, or otherwise violate any applicable local, state, national, or foreign law or regulation; or<br/> 
    (c) advertises or otherwise solicits funds or is a solicitation for goods or services. Company reserves the right to terminate your use of the Service, and, if applicable, to delete any such material <br/>
    from its servers. Company intends to cooperate fully with any law enforcement officials or agencies in the investigation of any violation of these loan1 of Use or of any applicable laws.</p>

    <p className='loan1'>Copyright Infringement</p>
    <p >Company has in place certain legally mandated procedures regarding allegations of copyright infringement occurring on the Site or with the Service. Company has adopted a policy that provides for the 
    immediate suspension and/or termination of any user who is found to have infringed on the rights of Company or of a third party, or otherwise violated any intellectual property laws or regulations. 
    HomeRatesYard’s policy is to investigate any allegations of copyright infringement brought to its attention. If you have evidence, know, or have a good faith belief that your rights or the rights 
    of a third party have been violated and you want Company to delete, edit, or disable the material in question, you must provide Company with all of the following information: <br/>
    (a) a physical or electronic signature of a person authorized to act on behalf of the owner of the exclusive right that is allegedly infringed; <br/>
    (b) identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative list of such works; <br/>
    (c) identification of the material that is claimed to be infringed or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information 
    reasonably sufficient to permit Company to locate the material; <br/>
    (d) information reasonably sufficient to permit Company to contact you, such as an address, telephone number, and if available, an electronic mail address at which you may be contacted; <br/>
    (e) a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and <br/>
    (f) a statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. 
    For this notification to be effective, you must provide it to HomeRatesYard’s designated agent at:<br/>

    Thirumala Venkata Anand Mohan Dharmapuri<br/>
    HomeRatesYard<br/>
    Ashburn, Ashburn VA, 20148<br/>
    (404) 556-7894<br/>
    mortgage@vammortgage.com<br/> </p>

    <p className='loan1'>Alleged Violations</p>
    <p >Company reserves the right to terminate your use of the Service and/or the Site. To ensure that Company provides a high-quality experience for you and for other users of the Site and the Service, 
    you agree that Company or its representatives may access your account and records on a case-by-case basis to investigate complaints or allegations of abuse, infringement of third-party rights, 
    or other unauthorized uses of the Site or the Service. Company does not intend to disclose the existence or occurrence of such an investigation unless required by law, but Company reserves the 
    right to terminate your account or your access to the Site immediately, with or without notice to you, and without liability to you, if Company believes that you have violated any of the loan1 of Use, 
    furnished Company with false or misleading information, or interfered with use of the Site or the Service by others.</p>

    <p className='loan1'>Accessing the Website</p>
    <p >You agree and acknowledge that you have the sole responsibility and liability for your use of this website and for providing or obtaining, and for maintaining, all the hardware, software, electrical power, 
    telecommunications, Internet services, and other products or services necessary or desirable for you to access and use this website.</p>

    <p>From time to time, due to the performance of maintenance, malfunctions or failures of software, equipment, or telecommunications devices, unusual transaction volume, or similar reasons, the website may 
    not be available for your use. We minimize the periods of time during which website is unavailable. You agree that we shall not be responsible for any loss, damages, costs, or expenses which you may suffer 
    or incur, directly or indirectly, as a result of the unavailability of the website, regardless of whether it could be shown that we could have prevented or reduced the duration of such unavailability by 
    taking any action within our reasonable control. We shall also not be responsible for any loss, damages, costs, or expenses which you may suffer or incur, directly or indirectly, as a result of your 
    inability to access the website caused directly or indirectly, in whole or in part, by your computer or mobile device, your inability to establish a connection to the Internet, your Internet Service Provider 
    (“ISP”), or capacity or other limitations or constraints of the Internet.</p>

    <p >We may at any time, with or without cause, and without prior notice to you deny you access to the website. We may terminate these loan1 of Use and your access to the website in whole or in part at any time 
    without prior notice to you. In the event we terminate these loan1 of Use, any applications you have submitted will continue to be evaluated, and any existing transactions you have entered into with us shall 
    remain in effect.</p>

    <p >The website is not intended for use by persons outside of the state in which Company has been approved to offer mortgage loan products and services or in states where we have not received website approval 
    where such website approval is required. We may restrict your access to the website during times you are in a country for which use of the website would be prohibited. You are responsible for compliance with all local laws.</p>

    <p>To protect the security of your information, we may require you to authenticate your identity (i.e., prove that you are who you say you are) to conduct certain transactions on this website. It is a good idea to protect 
    your security by always closing your web browser after leaving the website. If you believe that information that you have submitted through the website has been used without your permission, you must tell us immediately. 
    Telephoning us is the best way of keeping your possible losses to a minimum. Call us at (404) 556-7894 to report unauthorized access. If you fail to notify us, you may be liable for all unauthorized activity on your account. 
    You can also contact us at (404) 556-7894 regarding technical issues with this website.</p>

    <p className='loan1'>SMS Consent</p>
    <p >Providing your telephone contact information to us means you have consented in writing to receive SMS communications (text messages) from us. When consenting to messaging notifications, you authorize Company, 
    our assigns, successors, or servicing agents to send SMS Notifications (as defined below) to any phone number provided to us, our assigns, successors, or service agents in connection with your account, application, loan, and closing. 
    As used in this text messaging disclosure, “SMS Account Notifications” means any SMS (text message) communications from us to you pertaining to your account or loan transaction sent to the phone number provided in connection with this transaction, 
    including but not limited to application processing status, account information, loan information, information requests, document requests, due dates, delinquent accounts, closings, and program updates. No Mobile information will be shared with third 
    parties/affiliates for marketing/promotional purposes. All the above categories exclude text messaging originator opt in data and consent; this information will not be shared with any third parties.</p>
            
    <p className= 'loan1'>How to Unsubscribe</p>
    <p >You may withdraw your consent to receive SMS Account Notifications by replying with “stop, end, cancel, unsubscribe, or quit” or by calling us at (404) 556-7894 at any time. We may treat your provision of an invalid mobile phone number, 
    or the subsequent malfunction of a previously valid mobile phone number, as a withdrawal of your consent to receive SMS Account Notifications. Any withdrawal of your consent to use SMS Account Notifications will be effective only after we have a reasonable 
    period of time to process your withdrawal. To request additional information, contact us by telephone at (404) 556-7894. In order to access, view, and retain SMS Account Notifications that we make available to you, you must have:<br/>
    (i) a SMS-capable mobile phone, <br/>
    (ii) an active mobile phone account with a communication service provider; and <br/>
    (iii) sufficient storage capacity on your mobile phone.</p>
              
    <p>All SMS Account Notifications in electronic format from us to you will be considered “in writing.”</p>
    <p >There is no service fee for SMS Account Notifications, but you are responsible for any and all charges, including but not limited to fees associated with text messaging, imposed by your communications service provider. 
    Please consult your mobile service carrier’s pricing plan to determine the charges for sending and receiving text messages. These charges will appear on your phone bill. Message frequency depends on account status or settings. 
    We may modify or terminate our text messaging services from time to time, for any reason, and without notice, including the right to terminate text messaging with or without notice, without liability to you.</p>

    <p className='loan1'> Prohibited Use</p>
    <p >Company imposes certain restrictions on your permissible use of the Site and the Service. You are prohibited from violating or attempting to violate any security features of the Site or Service, including, without limitation, <br/>
    (a) accessing content or data not intended for you, or logging onto a server or account that you are not authorized to access; <br/>
    (b) attempting to probe, scan, or test the vulnerability of the Service, the Site, or any associated system or network, or to breach security or authentication measures without proper authorization; <br/>
    (c) interfering or attempting to interfere with service to any user, host, or network, including, without limitation, by means of submitting a virus to the Site or Service, overloading, “flooding,” “spamming,” “mail bombing,” or “crashing;” <br/>
    (d) using the Site or Service to send unsolicited e-mail, including, without limitation, promotions, or advertisements for products or services; <br/>
    (e) forging any TCP/IP packet header or any part of the header information in any e-mail or in any posting using the Service; or <br/>
    (f) attempting to modify, reverse-engineer, decompile, disassemble, or otherwise reduce or attempt to reduce to a human-perceivable form any of the source code used by Company in providing the Site or Service. Any violation of system or network 
    security may subject you to civil and/or criminal liability.</p>

    <p className='loan1'>Your Information</p>
    <p >Please review our privacy policy to fully understand the way we use the information that you provide to us, or that we collect through other approved methods. During the process of your mortgage application, you may submit certain 
    information to us. We do not claim ownership of the materials you provide (including feedback and suggestions), post, upload, input, or submit to ahmcloans.com or any of its affiliated businesses (collectively “Your Information”). However, by posting, 
    uploading, inputting, providing, or submitting Your Information, you are granting us, our affiliated companies, and any vendors necessary to the course of your transaction permission to use Your Information to fulfill your request for services and for 
    purposes defined in our privacy policy. That permission includes, but is not limited to allowing us to copy, distribute, transmit, publicly display (we will never publicly display your non-public personal information), reproduce, edit, translate, and 
    reformat Your Information. Please note that specific loan1 and conditions provided on the web page describing a particular feature or offer may supersede this provision.</p>

    <p className='loan1'>Do Not Sell My Personal Information</p>
    <p>If you’re a California resident, the California Consumer Privacy Act (CCPA) permits you to request an opt-out of the “sale” of your Personal Information to third parties. Although we don’t sell your Personal Information in the traditional 
    sense, we’ll share your Personal Information with third parties once we receive your authorization. <br/>
    To submit an opt-out request, please email mortgage@vammortgage.com.</p>

    <p className='loan1'> Consent to Verifications</p>
    <p >By providing us with your information you are providing written consent permitting us to contact third parties as we deem it necessary to provide our services to you.</p>

    <p className='loan1'>Affiliated Sites</p>
    <p >Company has no control over, and no liability for any third-party websites or materials. Company works with a number of partners and affiliates whose Internet sites may 
    be linked with the Site. Because neither Company nor the Site has control over the content and performance of these partner and affiliate sites, Company makes no guarantees about the accuracy, 
    currency, content, or quality of the information provided by such sites, and Company assumes no responsibility for unintended, objectionable, inaccurate, misleading, or unlawful content that may 
    reside on those sites. Similarly, from time to time in connection with your use of the Site, you may have access to content items (including, but not limited to, websites) that are owned by third parties.
    You acknowledge and agree that Company makes no guarantees about, and assumes no responsibility for, the accuracy, currency, content, or quality of this third-party content, and that, unless expressly provided otherwise, 
    these loan1 of Use shall govern your use of any and all third-party content.</p>

    <p className='loan1'>Indemnity</p>
    <p >You agree to indemnify Company for certain of your acts and omissions. You agree to indemnify, defend, and hold harmless Company, its affiliates, officers, directors, employees, consultants, agents, and representatives from any and all 
    third party claims, losses, liability, damages, and/or costs (including reasonable attorney fees and costs) arising from your access to or use of the Site, your violation of these loan1 of Use, or your infringement, or infringement by any other user of your account, 
    of any intellectual property or other right of any person or entity. Company will notify you promptly of any such claim, loss, liability, or demand, and will provide you with reasonable assistance, at your expense, in defending any such claim, loss, liability, 
    damage, or cost. You further agree that you will cooperate fully in the defense of any such claims. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and you shall 
    not in any event settle any such claim or matter without our written consent.</p>

    <p className='loan1'>Other loan1 & Conditions</p>
    <p > Equal Opportunity Employer The Company is an equal opportunity employer. Any complaints or concerns about the Company’s employment practices may be directed to the Director of Human Resources at (404) 556-7894.</p>

    <p className='loan1'>Copyright</p>
    <p >All contents of Site or Service are: Copyright © 2023, HomeRatesYard Ashburn, Ashburn VA, 20148. All rights reserved.</p>

    <p className='loan1'>Governing Law</p>
    <p >These loan1 of Use shall be construed in accordance with and governed by the laws of the United States, without reference to their rules regarding conflicts of law. You hereby irrevocably consent to the exclusive jurisdiction of the state or 
    federal courts in Orange County, California, USA in all disputes arising out of or related to the use of the Site or Service.</p>

    <p className='loan1'>Severability; Waiver</p>
    <p >If, for whatever reason, a court of competent jurisdiction finds any term or condition in these loan1 of Use to be unenforceable, all other loan1 and conditions will remain unaffected and in full force and effect. No waiver of any breach of 
    any provision of these loan1 of Use shall constitute a waiver of any prior, concurrent, or subsequent breach of the same or any other provisions hereof, and no waiver shall be effective unless made in writing and signed by an authorized representative of the waiving party.</p>

    <p className='loan1'>No License</p>
    <p >Nothing contained on the Site should be understood as granting you a license to use any of the trademarks, service marks, or logos owned by Company or by any third party.</p>

    <p className='loan1'>Modifications</p>
    <p >Company may, in its sole discretion and without prior notice, (a) revise these loan1 of Use; (b) modify the Site and/or the Service; and (c) discontinue the Site and/or Service at any time. Company shall post any revision to these loan1 of Use to the Site, 
    and the revision shall be effective immediately on such posting. You agree to review these loan1 of Use and other online policies posted on the Site periodically to be aware of any revisions. You agree that, by continuing to use or access the Site following notice of any revision, 
    you shall abide by any such revision.</p>

    <p className='loan1'>Acknowledgement</p>
    <p>By Using the Service or Accessing the Site, You Acknowledge That You Have Read These loan1 of Use and Agree to Be Bound by Them. You agree that we may from time to time amend all or any part of these loan1 of Use, including, without limitation, establishing, 
    increasing, or decreasing the fees and charges for products and services made available through this website and changing the features and functionality to this website. We will notify you electronically of any change to these loan1 of Use by posting updates here or as otherwise 
    required by applicable law. Your use of the website after the effective date of the change shall constitute your agreement to be bound by the loan1 of the change. You should also review these loan1 of Use periodically for any changes.</p>   
    </div>
</div>
    <div className="col-sm-12 col-md-12 col-lg-7 get1">
            <div className="m-4 mx-5">
        <p className="offers1">Prequalify now with the Homeratesyard <br/>Digital Mortgage Experience</p>

        </div>
        </div>
        <div className="col-sm-12 col-md-12 col-lg-5 text-center get3">
          <div className="mt-5">
          <Link href="/Signup"><button className="Home-buyer-button mt-1 mb-2 mx-2">Get Started</button></Link>
          <Link href="/MortgageLoan"><button className="Home-buyer-button mt-1 mb-2" onClick={() => setModalShow(true)}>Learn More</button></Link>
        </div>
        <Step
          show={modalShow}
          onHide={() => setModalShow(false)}
          />
      </div>
      </div>
      </div>
    </>
  );
}

export default loan1;
